# This is a basic workflow to help you get started with Actions

name: CI
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kuzeytech'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm install
      - run: npm run prepublish
      - run: npm publish dist/my-component-app/browser
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}